name: llm
channels:
  - defaults
dependencies:
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - cython
      - ema-workbench
      - hdbscan
      - huggingface-hub
      - secrets
      - llama-cpp-python
      - llama-index
      - matplotlib
      - numba
      - numpy
      - pandas
      - pdfminer-six
      - pymupdf
      - pymupdfb
      - python-dotenv
      - scikit-learn
      - scipy
      - seaborn
      - torch
      - transformers
      - umap-learn
