name: llm
channels:
  - defaults
  - pytorch 
  - nvidia
dependencies:
  - pytorch
  - torchvision
  - torchaudio 
  - pytorch-cuda=12.1 
  - hdbscan
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - umap-learn
  - ipykernel
  - jupyter
  - ipywidgets
  - pip:
      - ema-workbench
      - huggingface-hub
      - llama-cpp-python
      - llama-index==0.9.15
      - python-dotenv
      - transformers
      - ipyfilechooser 
      - accelerate
      - pypdf
