name: llm
channels:
  - defaults
dependencies:
  - hdbscan
  - numpy
  - pandas
  - python=3.9
  - scikit-learn
  - seaborn
  - umap-learn
  - ipykernel
  - ipywidgets
  - pip:
      - ema-workbench
      - huggingface-hub
      - llama-cpp-python
      - llama-index=0.9.15
      - python-dotenv
      - torch
      - transformers
      - transformers[torch]
      - ipyfilechooser 
      - accelerate
      - pypdf
