name: llm
channels:
  - conda-forge
  - pytorch 
  - nvidia
dependencies:
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - hdbscan
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - umap-learn
  - openai
  - spacy
  - networkx
  - matplotlib
  - plotly
  - freetype=2.10.4
  - python-docx
  - python-dotenv
  - bibtexparser
  - python-flair
  - accelerate=0.26.1
  - ipyfilechooser=0.6.0
  - datasets=2.16.1
  - transformers=4.34.0
  - pypdf=4.0.0
  - llama-index=0.9.15
  - bertopic=0.15.0
  - spacy==3.5.3