name: llm
channels:
  - conda-forge
  - pytorch 
  - nvidia
dependencies:
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - hdbscan
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - umap-learn
  - openai
  - spacy
  - networkx
  - matplotlib
  - plotly
  - freetype=2.10.4
  - python-docx
  - python-dotenv
  - bibtexparser