name: llm
channels:
  - defaults
  - pytorch 
dependencies:
  - hdbscan
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - umap-learn
  - ipykernel
  - ipywidgets
  - pip:
      - ema-workbench
      - huggingface-hub
      - llama-cpp-python
      - llama-index==0.9.15
      - python-dotenv
      - transformers
      - ipyfilechooser 
      - accelerate
      - pypdf
