name: llm
channels:
  - defaults
  - pytorch 
  - nvidia
dependencies:
  - hdbscan
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - umap-learn
  - ipykernel
  - ipywidgets
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1 
  - pip:
      - huggingface-hub
      - llama-index==0.9.15
      - transformers
      - accelerate
      - pypdf
      - ipyfilechooser