name: llm
channels:
  - conda-forge
  - pytorch 
  - nvidia
dependencies:
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - hdbscan
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - spacy
  - scikit-learn
  - seaborn
  - umap-learn
  - accelerate
  - ollama
  - llama-index
  - transformers>=0.20
  - bitsandbytes
  - peft
